name: Run React Web App

on:
  push:
    branches:
      - main
    paths:
      - src/chess-app/*
      - src/chess-app-backend/*
  pull_request:
    branches:
      - main
    paths:
      - src/chess-app/*
      - src/chess-app-backend/*

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Start front-end web app
        working-directory: ./src/chess-app
        run: |
          npm install
          npm start

      - name: Start back-end server
        working-directory: ./src/chess-app-backend
        run: |
          npm install
          npm start
          
      # Integrate deployment once we find someone to host us

#       - name: Deploy to server
#         uses: easingthemes/ssh-deploy@v2.1.5
#         with:
#           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#           remote-user: ${{ secrets.SERVER_USER }}
#           hostname: ${{ secrets.SERVER_IP }}
#           remote-dir: /var/www/my-app
#           local-dir: build
#           args: --delete

#       - name: Test deployment
#         run: |
#           curl -I https://example.com
